NAOSecurityBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: NAOSecurityBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: '64'
            unique: true
        password:
            type: string
            length: '100'
        email:
            type: string
            length: '64'
            unique: true
        isActive:
            type: boolean
        roles:
            type: array
    lifecycleCallbacks: {  }
