<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    //Récupère les articles et utilise le paginator
    public function getArticles($page, $nbreParPage)
    {
        $queryBuilder = $this->createQueryBuilder('a');
        $queryBuilder->orderBy('a.id', 'DESC'); //Ordonne par ordre décroissant dernier article au premier article
        $query = $queryBuilder->getQuery();

        $query
            //On définit l'article à partir duquel commencer la liste
            ->setFirstResult(($page-1) * $nbreParPage)
            //Le nombre d'épisode à afficher sur une page
            ->setMaxResults($nbreParPage);


        return new Paginator($query, true);
    }

    //Récupère les articles pour utilisation dans articles récents et le limit à 3 résultats
    public function getArticlesTotal()
    {
        $queryBuilder = $this->createQueryBuilder('a');
        $queryBuilder->orderBy('a.id', 'DESC');//Ordonne par ordre décroissant dernier article au premier article
        $query = $queryBuilder->getQuery();
        $query->setMaxResults(3); //Limite à 3 résultats.

        return $query->getResult();
    }
}
