<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends EntityRepository
{
    public function getObservationInfoWithMailleByBird($birdId)
    {
        $list = $this->createQueryBuilder('o')
            ->where('o.bird = :birdId')
            ->setParameter('birdId', $birdId)
//            ->andWhere('o.validated = true')
            ->leftJoin('o.km10Maille', 'km')
            ->addSelect('km')
            ->getQuery()
            ->getResult();
        return $list;
    }

    public function getOneMailleGeoJsonByBird($birdId)
    {

    }

    /**
     *
     */
    public function find10ByBird($bird){

            return $this->findBy(array("bird" => $bird), array('id' => 'DESC','date' => 'DESC'));
    }
}
