app:
    resource: '@AppBundle/Controller/'
consultation:
    path:    /bird/{id}
    defaults:
        _controller: AppBundle:Results:getBirdsResults
    requirements:
        id:

    type: annotation

login_check:
    path: /login_check

logout:
    path: /logout
