app:
    resource: '@AppBundle/Controller/'
    type: annotation

home_page:
    path:    /{page}
    defaults:
        _controller: AppBundle:Home:index
        page:        1
    requirements:
        page: \d+

observation:
    path:    /observation
    defaults:
        _controller: AppBundle:Observation:observation

results:
    path:    /results
    defaults:
        _controller: AppBundle:Results:results



join:
    path:    /join
    defaults:
        _controller: AppBundle:Join:join

donate:
    path:    /donate
    defaults:
        _controller: AppBundle:Donate:donate

admin_account:
    path:    /admin-account
    defaults:
        _controller: AppBundle:AdminAccount:adminAccount

admin_dashboard:
    path:    /a-dashboard
    defaults:
        _controller: AppBundle:AdminDashboard:adminDashboard

account:
    path:    /account
    defaults:
        _controller: AppBundle:Account:account

login:
    path:    /login
    defaults:
        _controller: AppBundle:Login:login

create_account:
    path:    /create-account
    defaults:
        _controller: AppBundle:CreateAccount:createAccount

login_check:
    path: /login_check

logout:
    path: /logout
