home_page:
    path:    /{page}
    defaults:
        _controller: AppBundle:Home:index
        page:        1
    requirements:
        page: \d+

observation:
    path:    /observation
    defaults:
        _controller: AppBundle:Observation:observation

observation_edit:
    path:    /observation/edit/{id}
    defaults:
        _controller: AppBundle:Observation:observationEdit
    requirements:
        id:  \d+

observation_remove:
    path:    /observation/remove/{id}
    defaults:
        _controller: AppBundle:Observation:observationRemove
    requirements:
        id:  \d+

observation_validate:
    path:    /observation/validate/{id}
    defaults:
        _controller: AppBundle:Observation:observationValid
    requirements:
        id:  \d+

results:
    path:    /results
    defaults:
        _controller: AppBundle:Results:results

blog:
    resource: '@AppBundle/Controller/BlogController.php'
    type:     annotation

contact:
    resource: '@AppBundle/Controller/ContactController.php'
    type:     annotation


legal_notice:
    resource: '@AppBundle/Controller/LegalController.php'
    type:     annotation


join:
    path:    /join
    defaults:
        _controller: AppBundle:Join:join

donate:
    path:    /donate
    defaults:
        _controller: AppBundle:Donate:donate

admin_user:
    path:    /admin/user
    defaults:
        _controller: AppBundle:AdminGestionUser:adminGestionUser

admin_article:
    path:    /admin/article
    defaults:
        _controller: AppBundle:AdminGestionArticle:adminGestionArticle

admin_rapport:
    path:    /admin/rapport
    defaults:
        _controller: AppBundle:AdminGestionRapport:adminGestionRapport

account:
    path:    /account
    defaults:
        _controller: AppBundle:AccountProfil:account

account_observation:
    path:    /account/observation
    defaults:
        _controller: AppBundle:AccountObservation:observation

account_validation:
    path:    /account/validation
    defaults:
        _controller: AppBundle:AccountValidation:validation

login:
    path:    /login
    defaults:
        _controller: AppBundle:Login:login

create_account:
    path:    /create-account
    defaults:
        _controller: AppBundle:CreateAccount:createAccount

login_check:
    path: /login_check

logout:
    path: /logout
