# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
            NAOSecurityBundle\Entity\User:
                algorithm: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
           entity:
              class: NAOSecurityBundle:User
              property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            anonymous:  true
            http_basic: ~
            provider: main
            form_login:
              login_path: /login
              check_path: /login_check
            logout:
              path:       /logout
              target:     /

