# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
            AppBundle\Entity\User:
                algorithm: bcrypt

    role_hierarchy:
        ROLE_VALIDATEUR:    ROLE_USER
        ROLE_ADMIN:        [ROLE_USER, ROLE_VALIDATEUR]
        ROLE_SUPER_ADMIN:  [ROLE_USER, ROLE_VALIDATEUR, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
           entity:
              class: AppBundle:User
              property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            anonymous:  true
            http_basic: ~
            provider: main
            form_login:
              login_path: /login
              check_path: /login_check
            logout:
              path:       /logout
              target:     /

    access_control:
        - { path: ^/account, roles: ROLE_USER }
        - { path: ^/a-dashboard, roles: ROLE_ADMIN }