# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    observation.recording:
        class: AppBundle\Services\ObservationRecording
        arguments: ["@doctrine.orm.entity_manager", %birds_images%]

    appbundle.user_service:
         class: AppBundle\Services\UserService
         arguments: ["@doctrine.orm.entity_manager","@security.password_encoder"]

    out_of_france_validator:
         class: AppBundle\Validator\Constraints\OutOfFranceValidator
         arguments:
             - "@doctrine.orm.entity_manager"
         tags:
            - {name: validator.constraint_validator}