# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    observation.recording:
        class: AppBundle\Services\ObservationRecording
        arguments:
            - "@doctrine.orm.entity_manager"

    maille.finder:
        class: AppBundle\Services\MailleFinder
        arguments:
            - "@doctrine.orm.entity_manager"
    appbundle.user_service:
      class: AppBundle\Services\UserService
      arguments: ["@doctrine.orm.entity_manager","@security.password_encoder"]