# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    observation.persist:
        class: AppBundle\Services\ObservationPersist
        arguments:
            - "@doctrine.orm.entity_manager"
    appbundle.user_service:
      class: AppBundle\Services\UserService
      arguments: ["@doctrine.orm.entity_manager","@security.password_encoder"]