# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    observation_manager:
        class: AppBundle\Services\ObservationManager
        arguments: ["@doctrine.orm.entity_manager"]

    observation_assembleur:
            class: AppBundle\Services\ObservationAssembleur
            arguments: ["@doctrine.orm.entity_manager"]

    image_manager:
        class: AppBundle\Services\ImageManager
        arguments: [ %birds_images%]

    mail:
        class: AppBundle\Services\ContactService
        arguments:
            - "@mailer"
            - "@templating"

    appbundle.user_service:
         class: AppBundle\Services\UserService
         arguments: ["@doctrine.orm.entity_manager","@security.password_encoder"]

    data_to_geojson:
        class: AppBundle\Services\DataToGeoJson

    data_to_array_maille_nb_birds:
        class: AppBundle\Services\DataToArrayMailleNameAndNumberOfBirds

    data_to_array_for_autocomplete_consultation:
        class: AppBundle\Services\DataToArrayOfObjectsForAutocompleteConsultation

#Validators
    out_of_france_validator:
         class: AppBundle\Validator\Constraints\OutOfFranceValidator
         arguments:
             - "@doctrine.orm.entity_manager"
         tags:
            - {name: validator.constraint_validator}

    no_observations_found_validator:
         class: AppBundle\Validator\Constraints\NoObservationsFoundValidator
         arguments:
             - "@doctrine.orm.entity_manager"
         tags:
            - {name: validator.constraint_validator}

    username_validator:
         class: AppBundle\Validator\Constraints\UsernameConstraintValidator
         arguments:
             - "@doctrine.orm.entity_manager"
         tags:
            - {name: validator.constraint_validator}

    mail_validator:
             class: AppBundle\Validator\Constraints\EmailConstraintValidator
             arguments:
                 - "@doctrine.orm.entity_manager"
             tags:
                - {name: validator.constraint_validator}